services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Vendor\ContaoLivePreviewBundle\:
        resource: '../../*'
        exclude:
            - '../../ContaoManager/'
            - '../../DependencyInjection/'
            - '../../ContaoLivePreviewBundle.php'
