contao_live_preview_resolve:
    path: /contao/live-preview/resolve
    controller: ThinkDigital\ContaoLivePreview\Controller\PreviewResolverController
    methods: [GET]
    defaults:
        _scope: backend
        _token_check: false
